spring:
  application:
    name: product-cache-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
  info:
    component: Product Cache Service

logging: ##Uygulamadaki logları takip edebilmek için eklenen conf.
  level:
    root: debug
    ##root: off
    ##com.eleiatech:debug ## bu şekilde diyerek daha az ve daha az karışık log görebiliriz.

server:
  port: 9791

---

spring:
  config:
    activate:
      on-profile: localhost
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

feign:
  product-service:
    name: product-service
    url: http://localhost:8762

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/


---
spring:
  config:
    activate:
      on-profile: stage
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

feign:
  product-service:
    name: product-service
    url: http://zuul-edge-server:8762


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      default-zone: http://eureka-server:8761/eureka/